### ISSUE TITLE
Trin do not create dashboard

### ISSUE THREAD

**Issue by r4f4ss** [ethereum/trin#1551]
I am following trin book to run dashborad using docker: https://ethereum.github.io/trin/users/monitoring.html#metrics-setup-with-docker

In the last step, creation of dashboard (step 5 `cargo run -p trin -- create-dashboard`) I can not create a dashboard:

(logs with `RUST_BACKTRACE=1`)

```
      Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.43s
     Running `target/debug/trin create-dashboard`
thread 'main' panicked at ethportal-api/src/types/cli.rs:266:17:
Creating dashboard failed template is missing value for placeholder "protocol"
stack backtrace:
   0: rust_begin_unwind
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:74:14
   2: ethportal_api::types::cli::TrinConfig::new_from
             at ./ethportal-api/src/types/cli.rs:266:17
   3: ethportal_api::types::cli::TrinConfig::from_cli
             at ./ethportal-api/src/types/cli.rs:254:9
   4: trin::main::{{closure}}
             at ./src/main.rs:12:23
   5: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/future/future.rs:123:9
   6: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
             at <PATH>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/park.rs:281:63
   7: tokio::runtime::coop::with_budget
             at <PATH>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/coop.rs:107:5
   8: tokio::runtime::coop::budget
             at <PATH>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/coop.rs:73:5
   9: tokio::runtime::park::CachedParkThread::block_on
             at <PATH>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/park.rs:281:31
  10: tokio::runtime::context::blocking::BlockingRegionGuard::block_on
             at <PATH>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/context/blocking.rs:66:9
  11: tokio::runtime::scheduler::multi_thread::MultiThread::block_on::{{closure}}
             at <PATH>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/scheduler/multi_thread/mod.rs:87:13
  12: tokio::runtime::context::runtime::enter_runtime
             at <PATH>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/context/runtime.rs:65:16
  13: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
             at <PATH>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/scheduler/multi_thread/mod.rs:86:9
  14: tokio::runtime::runtime::Runtime::block_on_inner
             at <PATH>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/runtime.rs:363:45
  15: tokio::runtime::runtime::Runtime::block_on
             at <PATH>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/runtime.rs:333:13
  16: trin::main
             at ./src/main.rs:19:5
  17: core::ops::function::FnOnce::call_once
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

*This errro appear in the first run, if I re-run without delete data sources in Graphana I get other error as described in Trin book.

**Comment by Ktl-XV** [comment]
@KolbyML can you close this issue? It was solved with #1625
